server :
  protocol : http
  url : 127.0.0.1
  port : 8080
#  servlet :
#    context-path : /api

spring:
  h2.console.enabled: true
  datasource:
    url : jdbc:mysql://localhost:3306/switus
    username : inkyung
    password : password
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 2
    connectionTestQuery: SELECT 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  servlet:
    multipart: # Multipart properties
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true
  messages :
    basename : i18n/exception
    encoding : UTF-8

---
# Log
logging:
  level:
    org.hibernate.SQL : debug

# Log file
default:
  dir:
    path: /Users/inkyung/@Development/@Workspace/studywithus.back/
  log:
    path: ${default.dir.path}/logs

---
file:
  path :
    default : ${default.dir.path}/upload_files/
    cover-image : ${file.path.default}/cover_images/




---
spring:
  profiles:
    include: auth
