spring:
  jwt:
    secretKey : helloSwitus

---
# Goggle
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id : 761754848533-bdmp7u9iscoj5a67rogo5rhrnu7cubjg.apps.googleusercontent.com
            client-secret : rIyc5F4Gjmvw-wzcAEqj9zrv
            scope : profile, email

---
# Naver : 네이버에서는 Spring Security를 공식 지원하지 않으므로 구글과 달리 Common-OAuth2Provider에서 해주던 값들도 수동으로 입력해줘야 한다.
spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: aLiZWBmRXU5a01g8pmfy
            client-secret: RvfNklq128
            scope: name,email,profile_image
            redirect_uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response  # 네이버의 회원 조회 시 반환되는 JSON 형태인데, 정보에 대한 최상위 필드명이 response 이다
