spring:
  datasource:
    url : jdbc:mysql://localhost:3306/switus
    username : inkyung
    password : password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
