server :
  protocol : http
  url : 127.0.0.1
  port : 8080
#  servlet :
#    context-path : /api

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/switus
    username : inkyung
    password : password
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 2
    connectionTestQuery: SELECT 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    profiles:
      include: oauth

logging:
  level:
    org.hibernate.SQL : debug
