spring:
  profiles:
    include:
      - auth
      - database

---
server :
  port : 8443
  ssl :
    key-store : classpath:keystore.p12
    key-store-type : PKCS12
    key-store-password : switus1201

---
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart: # Multipart properties
      max-file-size: 200MB
      max-request-size: 215MB
      enabled: true
  messages :
    basename : i18n/exception
    encoding : UTF-8

---
# Log
logging:
  level:
    org.hibernate.SQL : debug

# Log file
default:
  dir:
    path: /home/inkyung/study_with_us/back
  log:
    path: ${default.dir.path}/logs

---
file:
  path :
    default : ${default.dir.path}/upload_files/
    cover-image : ${file.path.default}/cover_images/
    editor-image : ${file.path.default}/editor_images/
    attachment : ${file.path.default}/attchment/
