spring:
  datasource:
    url : jdbc:mysql://localhost:3306/switus?userUnicode=true
    username : inkyung
    password : password
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-name: hikari-cp
    maximum-pool-size: 30
    minimum-idle: 2
    connectionTestQuery: SELECT 1
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true